import SimilarTrack from 'types/similarTrack';

const similarTracks: SimilarTrack[] = [
  {
    name: 'So por uma noite',
    artist: {
      name: 'Charlie Brown Jr',
      mbid: '87',
      url: 'http://hedmigic.ps/pazatre',
    },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 228371,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'Me Adora',
    artist: { name: 'Pitty', mbid: '88', url: 'http://ijla.dk/tok' },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 39821,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'Tora Tora',
    artist: { name: 'Raimundos', mbid: '95', url: 'http://za.fk/im' },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 93821,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'Hold the Line',
    artist: { name: 'Toto', mbid: '64', url: 'http://suh.mw/pahol' },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 928173,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'All Star',
    artist: { name: 'Smash Mouth', mbid: '51', url: 'http://hilton.td/da' },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 3928174,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'Photograph',
    artist: { name: 'Nickelback', mbid: '21', url: 'http://di.ma/neli' },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 938174,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'Angels',
    artist: { name: 'Miley Cyrus', mbid: '20', url: 'http://fip.im/ivejenba' },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 392817,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'Out of Touch',
    artist: {
      name: 'John Oates and Daryl Hall',
      mbid: '66',
      url: 'http://uwpikwu.bm/hin',
    },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 383728,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'Uma criança com seu olhar',
    artist: { name: 'Charlie Brown Jr', mbid: '79', url: 'http://da.sb/vurvu' },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 383728,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'Um dia a gente se encontra',
    artist: { name: 'Charlie Brown Jr', mbid: '10', url: 'http://ewa.cz/di' },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 383728,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
  {
    name: 'Zoio de Lula',
    artist: {
      name: 'Charlie Brown Jr',
      mbid: '87',
      url: 'http://joftu.py/wocuvgol',
    },
    url: 'https://url.com/',
    streamable: 0,
    listeners: 383728,
    image: [
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
      { '#text': 'https://img.com' },
    ],
  },
];

export default similarTracks;
