import { Track } from 'api/fetchTrack';

const track: Track[] = [
  {
    name: 'So por uma noite',
    artist: 'Charlie Brown Jr',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 228371,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'Me Adora',
    artist: 'Pitty',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 39821,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'Tora Tora',
    artist: 'Raimundos',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 93821,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'Hold the Line',
    artist: 'Toto',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 928173,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'All Star',
    artist: 'Smash Mouth',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 3928174,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'Photograph',
    artist: 'Nickelback',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 938174,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'Angels',
    artist: 'Miley Cyrus',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 392817,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'Out of Touch',
    artist: 'John Oates and Daryl Hall',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 383728,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'So por uma noite',
    artist: 'Charlie Brown Jr',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 383728,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'So por uma noite',
    artist: 'Charlie Brown Jr',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 383728,
    image: [{ '#text': 'https://img.com' }],
  },
  {
    name: 'So por uma noite',
    artist: 'Charlie Brown Jr',
    url: 'https://url.com/',
    streamable: 0,
    listeners: 383728,
    image: [{ '#text': 'https://img.com' }],
  },
];

export default track;
